import type { GameData } from "@/types";

export function generateDemoGameData(): GameData {
  const teams = [
    { id: "teamA", label: "Blue", color: "#0033cc" },
    { id: "teamB", label: "Red", color: "#cc0000" },
  ];

  const events = [
    {
      id: "evt-001",
      type: "score" as const,
      teamId: "teamA",
      playerId: "23",
      scoreDelta: 2,
      shotType: "2pt" as const,
      timestamp: 12.4,
      confidence: 0.85,
      source: "visual-ball-tracking",
      notes: "Detected visually: ball through hoop, 2pt shot (+2 points)",
    },
    {
      id: "evt-002",
      type: "shot_attempt" as const,
      teamId: "teamB",
      playerId: "15",
      timestamp: 18.7,
      confidence: 0.72,
      source: "pose+ball-heuristic",
      notes: "Detected by pose and ball tracking",
    },
    {
      id: "evt-002b",
      type: "dunk" as const,
      teamId: "teamA",
      playerId: "34",
      timestamp: 25.3,
      confidence: 0.88,
      source: "pose-analysis",
      notes: "Dunk detected: arms extended above head near hoop",
    },
    {
      id: "evt-002c",
      type: "block" as const,
      teamId: "teamB",
      playerId: "12",
      timestamp: 32.1,
      confidence: 0.75,
      source: "pose-analysis",
      notes: "Defensive block detected: raised arms near shooter",
    },
    {
      id: "evt-003",
      type: "missed_shot" as const,
      teamId: "teamB",
      timestamp: 19.2,
      confidence: 0.68,
      source: "pose-only",
      notes: "Shot attempt without score change",
    },
    {
      id: "evt-004",
      type: "defensive_rebound" as const,
      teamId: "teamA",
      timestamp: 19.8,
      confidence: 0.75,
      source: "ball+proximity-heuristic",
      notes: "Defensive rebound by Blue team",
    },
    {
      id: "evt-005",
      type: "score" as const,
      teamId: "teamA",
      scoreDelta: 3,
      shotType: "3pt" as const,
      timestamp: 45.2,
      confidence: 0.95,
      source: "ocr",
      notes: "3-point shot detected by scoreboard OCR",
    },
    {
      id: "evt-006",
      type: "turnover" as const,
      teamId: "teamB",
      timestamp: 67.1,
      confidence: 0.58,
      source: "possession-heuristic",
      notes: "Turnover detected by possession change",
    },
    {
      id: "evt-007",
      type: "shot_attempt" as const,
      teamId: "teamA",
      timestamp: 89.3,
      confidence: 0.82,
      source: "pose+ball-heuristic",
      notes: "Shot attempt with ball tracking",
    },
    {
      id: "evt-008",
      type: "offensive_rebound" as const,
      teamId: "teamA",
      timestamp: 90.1,
      confidence: 0.71,
      source: "ball+proximity-heuristic",
      notes: "Offensive rebound by Blue team",
    },
    {
      id: "evt-009",
      type: "score" as const,
      teamId: "teamA",
      scoreDelta: 2,
      shotType: "2pt" as const,
      timestamp: 91.5,
      confidence: 0.96,
      source: "ocr",
      notes: "Score detected by scoreboard OCR - 2-point score",
    },
    {
      id: "evt-010",
      type: "3pt" as const,
      teamId: "teamB",
      timestamp: 112.8,
      confidence: 0.45,
      source: "court-geometry-heuristic",
      notes: "Estimated 3-point attempt based on court position",
    },
    {
      id: "evt-011",
      type: "score" as const,
      teamId: "teamB",
      scoreDelta: 3,
      shotType: "3pt" as const,
      timestamp: 115.3,
      confidence: 0.92,
      source: "ocr",
      notes: "3-point score by Red team",
    },
    {
      id: "evt-012",
      type: "score" as const,
      teamId: "teamB",
      scoreDelta: 2,
      shotType: "2pt" as const,
      timestamp: 128.7,
      confidence: 0.89,
      source: "ocr",
      notes: "2-point score by Red team",
    },
  ];

  const summary = {
    teamA: {
      points: 7, // 2 + 3 + 2 = 7
      twoPointScores: 2,
      threePointScores: 1,
      foulShots: 0,
      shotAttempts: 3,
      offRebounds: 1,
      defRebounds: 1,
      turnovers: 0,
      threePointAttempts: 1,
      blocks: 0,
      dunks: 1,
      assists: 0,
      passes: 0,
      dribbles: 0,
      players: [
        {
          playerId: "23",
          points: 2,
          twoPointScores: 1,
          threePointScores: 0,
          foulShots: 0,
          shotAttempts: 1,
          twoPointAttempts: 1,
          threePointAttempts: 0,
          hitRate: 100,
          dunks: 0,
          blocks: 0,
          offRebounds: 0,
          defRebounds: 0,
          assists: 0,
          turnovers: 0,
          passes: 0,
          dribbles: 0,
        },
        {
          playerId: "34",
          points: 2,
          twoPointScores: 0,
          threePointScores: 0,
          foulShots: 0,
          shotAttempts: 0,
          twoPointAttempts: 0,
          threePointAttempts: 0,
          hitRate: 0,
          dunks: 1,
          blocks: 0,
          offRebounds: 0,
          defRebounds: 0,
          assists: 0,
          turnovers: 0,
          passes: 0,
          dribbles: 0,
        },
      ],
    },
    teamB: {
      points: 5,
      twoPointScores: 1,
      threePointScores: 1,
      foulShots: 0,
      shotAttempts: 2,
      offRebounds: 0,
      defRebounds: 0,
      turnovers: 1,
      threePointAttempts: 1,
      blocks: 1,
      dunks: 0,
      assists: 0,
      passes: 0,
      dribbles: 0,
      players: [
        {
          playerId: "15",
          points: 0,
          twoPointScores: 0,
          threePointScores: 0,
          foulShots: 0,
          shotAttempts: 1,
          twoPointAttempts: 1,
          threePointAttempts: 0,
          hitRate: 0,
          dunks: 0,
          blocks: 0,
          offRebounds: 0,
          defRebounds: 0,
          assists: 0,
          turnovers: 0,
          passes: 0,
          dribbles: 0,
        },
        {
          playerId: "12",
          points: 0,
          twoPointScores: 0,
          threePointScores: 0,
          foulShots: 0,
          shotAttempts: 0,
          twoPointAttempts: 0,
          threePointAttempts: 0,
          hitRate: 0,
          dunks: 0,
          blocks: 1,
          offRebounds: 0,
          defRebounds: 0,
          assists: 0,
          turnovers: 0,
          passes: 0,
          dribbles: 0,
        },
      ],
    },
  };

  return {
    video: {
      filename: "demo_basketball_game.mp4",
      duration: 125.4,
    },
    teams,
    events,
    summary,
  };
}
